name: Deploy to Home Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    # Use self-hosted runner with the label 'self-hosted'
    runs-on: [self-hosted, linux]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      working-directory: ./backend
      run: npm ci
    
    - name: Build backend
      working-directory: ./backend
      run: npm run build

    - name: Deploy application
      run: |
        set -e
        echo "=== Starting deployment ==="
        
        # Create directory if it doesn't exist
        sudo mkdir -p /var/www/projects/email-tracker
        sudo chown -R $USER:$USER /var/www/projects/email-tracker
        cd /var/www/projects/email-tracker
        
        # Clone or update the repository
        if [ -d .git ]; then
          echo "Updating repository..."
          git fetch origin
          git reset --hard origin/main
        else
          echo "Cloning repository..."
          git clone https://github.com/jacobmr/email-tracker.git .
        fi
        
        echo "Installing dependencies..."
        cd backend
        npm ci --production
        
        echo "Restarting PM2 process..."
        pm2 delete email-tracker 2> /dev/null || true
        NODE_ENV=production pm2 start src/index.js --name email-tracker --env production --port 3001
        pm2 save
        
        echo "=== Deployment completed successfully ==="

    - name: Verify deployment
      run: |
        echo "Deployment completed. Check the dashboard at https://e.brasilito.org/dashboard"
