name: Deploy to Home Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'backend/package-lock.json'

    - name: Install backend dependencies
      working-directory: ./backend
      run: npm ci

    - name: Build backend
      working-directory: ./backend
      run: npm run build

    - name: Setup SSH
      run: |
        # Create .ssh directory with proper permissions
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        
        # Add the server's host key to known_hosts
        ssh-keyscan -H 172.28.108.247 > ~/.ssh/known_hosts 2>/dev/null
        chmod 600 ~/.ssh/known_hosts
        
        # Save the private key with proper formatting
        cat << 'EOF' > ~/.ssh/deploy_key
        ${{ secrets.HOME_SERVER_SSH_KEY }}
        EOF
        chmod 600 ~/.ssh/deploy_key
        
        # Verify the key was saved correctly (debug)
        echo "=== Key file content (first 10 chars) ==="
        head -c 10 ~/.ssh/deploy_key || true
        echo "..."
        echo "======================================="
        
    - name: Deploy to home server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 172.28.108.247
        username: jacob
        key: ${{ secrets.HOME_SERVER_SSH_KEY }}
        script: |
          set -e
          echo "=== Starting deployment ==="
          
          # Create directory if it doesn't exist
          mkdir -p /var/www/projects/email-tracker
          cd /var/www/projects/email-tracker
          
          # Clone or update the repository
          if [ -d .git ]; then
            echo "Updating repository..."
            git fetch origin
            git reset --hard origin/main
          else
            echo "Cloning repository..."
            git clone https://github.com/jacobmr/email-tracker.git .
          fi
          
          echo "Installing dependencies..."
          cd backend
          npm ci --production
          
          echo "Restarting PM2 process..."
          pm2 delete email-tracker 2> /dev/null || true
          NODE_ENV=production pm2 start src/index.js --name email-tracker --env production --port 3001
          pm2 save
          
          echo "=== Deployment completed successfully ==="

    - name: Verify deployment
      run: |
        echo "Deployment completed. Check the dashboard at https://e.brasilito.org/dashboard"
